[package]
name = "homecloud-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP API for HomeCloud."

[[bin]]
name = "homecloud-api"
path = "src/main.rs"

[dependencies]
homecloud-domain.workspace = true

anyhow.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
